---
title: "r_solo-bdfinlayson"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(readr)
library(dplyr)
library(stringr)
```

## 1

```{r}

districts <- read_csv('./data/districts.csv')

nrows <- districts %>% 
  count()

ncols <- districts %>% 
  ncol()

str_interp("There are ${nrows} rows and ${ncols} columns")

```


## 2

```{r}

districts <- districts[-1,]

districts %>% head()
```

## 3

```{r}

ndistricts_proficiency_80 <- districts %>%
  filter(alg_1 >= 80 & eng_1 >= 80) %>% 
  summarize(n_distinct(system))

str_interp("There are ${ndistricts_proficiency_80} districts with alg and eng proficiency greater than 80%")
```

## 4
```{r}
ndistricts_proficiency_50 <- districts %>% 
  filter(alg_1 < 50 | eng_1 < 50) %>% 
  summarise(n_distinct(system))

str_interp("There are ${ndistricts_proficiency_50} districts with alg and eng proficiency less than 50%")
```

## 5
```{r}
lowest_grad_rate_district <- districts %>% 
  arrange(asc(grad)) %>% 
  top_n(1)

str_interp("There ${lowest_grad_rate_district} had the lowest graduation rate")
```


